Update Node API `data_available` and Light Doc Cleanups
celestiaorg/docs pull request #141
Opened 2022-06-08 15:07 UTC by YazzyYaz

Closes https://github.com/celestiaorg/docs/issues/140

2022-06-08 16:55 UTC, adlerjohn commented on docs/developers/instantiate-testnet.md
> -The following hardware minimum requirements are recommended for running the
One PR per issue. Do this or that in a separate PR.

2022-06-08 16:55 UTC, adlerjohn commented on docs/developers/node-tutorial.md
> +### Install Celestia Node
ditto

2022-06-10 13:23 UTC, adlerjohn commented
Converting to draft until unblocked by https://github.com/celestiaorg/celestia-node/pull/802 being finalized.

2022-07-04 16:16 UTC, renaynay requested changes

2022-07-04 16:16 UTC, renaynay commented on docs/developers/node-api.md
> +}
```suggestion
{"available":true,"probability_of_availability":"0.9899774042423815"}
```

2022-07-04 16:41 UTC, renaynay commented on docs/developers/node-api.md
> +Returns whether data is available at a specific block height.
```suggestion
Returns whether data is available at a specific block height and the probability that it is available based on the amount of samples collected.
```

2022-07-04 16:43 UTC, renaynay approved these changes

2022-07-04 16:47 UTC, merged