Update instances of `Optimint` to `Rollmint`
celestiaorg/docs pull request #249
Opened 2022-10-04 16:38 UTC by jcstein

Also add new image and update

2022-10-06 19:29 UTC, tzdybal commented on docs/developers/cosmwasm-dependency.md
> +go mod edit -replace github.com/cosmos/cosmos-sdk=github.com/celestiaorg/cosmos-sdk@v0.45.4-rollmint-v0.3.5
```suggestion
go mod edit -replace github.com/cosmos/cosmos-sdk=github.com/celestiaorg/cosmos-sdk-rollmint@v0.46.1-rollmint-v0.4.0
```

2022-10-06 19:29 UTC, tzdybal commented on docs/developers/install-optimint.md
> +go mod edit -replace github.com/cosmos/cosmos-sdk=github.com/celestiaorg/cosmos-sdk@v0.45.4-rollmint-v0.3.5
```suggestion
go mod edit -replace github.com/cosmos/cosmos-sdk=github.com/celestiaorg/cosmos-sdk-rollmint@v0.46.1-rollmint-v0.4.0
```

2022-10-06 19:36 UTC, tzdybal requested changes
You need to rename `install-optimint.md` to `install-rollmint.md`, because link is already updated.
Probably, you should also rename `optimint.md` to `rollmint.md` and fix links (if any). It seems that translation files also contains references to those files.

I also suggested the correct version of rollmint in comments.

2022-10-07 16:10 UTC, jcstein commented
changes added, thanks again @tzdybal

2022-10-10 13:18 UTC, tzdybal approved these changes
LGTM :)

2022-10-10 13:19 UTC, merged