Update full-stack-modular-development-guide.md
celestiaorg/docs pull request #401
Opened 2023-01-10 21:47 UTC by pynchmeister

## Overview

Changed ```Next.js``` to React.js

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-01-12 21:22 UTC, jcstein requested changes
hmm, this tutorial is still for a React app using Vite. what's the reason for the change?

2023-01-13 19:22 UTC, pynchmeister commented
Yes this tutorial is for a React app using Vite. The inclusion of Next.js seems to be a typo, though...

<img width="586" alt="Screen Shot 2023-01-13 at 2 21 49 PM" src="https://user-images.githubusercontent.com/33232379/212401510-26f198a1-5570-40be-881b-d56248efc4fc.png">

2023-01-13 19:57 UTC, jcstein requested changes

2023-01-13 19:57 UTC, jcstein commented on docs/developers/full-stack-modular-development-guide.md
> +Create a file named `.env.local` in the `src` directory and add the following
```suggestion
Create a file named `.env.local` in the `frontend/` directory and add the following
```

2023-01-13 19:58 UTC, jcstein commented
read this backwards lol. thank you, lgtm after the requested change. the `.env.local` file will go in the root of the React app directory, so in the `frontend/` dir

2023-01-13 20:01 UTC, pynchmeister commented
Sounds good to me, cheers

2023-01-13 20:02 UTC, jcstein approved these changes
LGTM

2023-01-13 20:07 UTC, merged