update: fix p2p network label for 0.6.1 arabica
celestiaorg/docs pull request #408
Opened 2023-01-12 14:04 UTC by derrandz

## Overview

This PR changes a few commands to use `arabica-2` when wanting to run against arabica using `0.6.1`, commands include:

- init command
- key generation command
- start command

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-01-13 20:46 UTC, jcstein commented on docs/nodes/light-node.mdx
> +celestia light init --p2p.network arabica-2
```suggestion
celestia light init --p2p.network arabica
```

2023-01-13 20:46 UTC, jcstein commented on docs/nodes/light-node.mdx
> +$ celestia light init --p2p.network arabica-2
```suggestion
$ celestia light init --p2p.network arabica
```

2023-01-13 20:46 UTC, jcstein commented on docs/nodes/light-node.mdx
> +celestia light start --core.ip <ip-address> --core.grpc.port <port> --gateway --gateway.addr <ip-address> --gateway.port <port> --p2p.network arabica-2
```suggestion
celestia light start --core.ip <ip-address> --core.grpc.port <port> --gateway --gateway.addr <ip-address> --gateway.port <port> --p2p.network <network>
```

2023-01-13 20:47 UTC, jcstein commented on docs/nodes/light-node.mdx
> +celestia light start --core.ip <ip-address> --core.grpc.port <port> --gateway --gateway.addr <ip-address> --gateway.port <port> --p2p.network arabica-2
although this is an arabica command, for sake of formatting, will keep same as rest of command. i.e. `<network>` instead of `arabica` or `arabica-2`

2023-01-13 20:47 UTC, jcstein commented on docs/nodes/light-node.mdx
> +celestia light start --core.ip https://limani.celestia-devops.dev --core.grpc.port 9090 --gateway --gateway.addr 127.0.0.1 --gateway.port 26659 --p2p.network arabica-2
```suggestion
celestia light start --core.ip https://limani.celestia-devops.dev --core.grpc.port 9090 --gateway --gateway.addr 127.0.0.1 --gateway.port 26659 --p2p.network arabica
```

2023-01-13 20:47 UTC, jcstein commented on docs/nodes/light-node.mdx
> +celestia light start --keyring.accname <key_name> --core.ip <ip-address> --core.grpc.port <port> --gateway --gateway.addr <ip-address> --gateway.port <port> --p2p.network arabica-2
```suggestion
celestia light start --keyring.accname <key_name> --core.ip <ip-address> --core.grpc.port <port> --gateway --gateway.addr <ip-address> --gateway.port <port> --p2p.network arabica
```

2023-01-13 20:48 UTC, jcstein commented on docs/nodes/light-node.mdx
> +celestia light start --core.ip <ip-address> --core.grpc.port <port> --keyring.accname <name_of_custom_key> --gateway --gateway.addr <ip-address> --gateway.port <port> --p2p.network arabica-2
```suggestion
celestia light start --core.ip <ip-address> --core.grpc.port <port> --keyring.accname <name_of_custom_key> --gateway --gateway.addr <ip-address> --gateway.port <port> --p2p.network arabica
```

2023-01-13 20:48 UTC, jcstein requested changes
left some changes! going to push some changes to your branch as well

2023-01-13 21:04 UTC, jcstein approved these changes
LGTM - we should add with https://github.com/celestiaorg/docs/pull/381 when `v0.6.2` is released, as currently, `./cel-key` does not use `--p2p.network` (https://github.com/celestiaorg/celestia-node/pull/1590)

2023-01-15 14:30 UTC, derrandz commented
@jcstein thanks for hopping on this, LGTM as well 👍🏻

2023-01-16 13:22 UTC, merged