ITN P2
celestiaorg/docs pull request #561
Opened 2023-03-27 15:33 UTC by YazzyYaz

2023-03-27 16:12 UTC, jcstein requested changes
added some changes in sentence case

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/blockspace-race.md
> +| [Write a technical article](./itn-setup-writeup.md) | Bonus  | Bonus Pool |
```suggestion
| [Write a technical article](./itn-setup-writeup.md) | Bonus  | Bonus pool |
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/blockspace-race.md
> +| [Run a public seed or RPC node](./itn-rpc-node.md) | Bonus | Bonus Pool |
```suggestion
| [Run a public seed or RPC node](./itn-rpc-node.md) | Bonus | Bonus pool |
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/blockspace-race.md
> +| [Write a technical article](./itn-setup-writeup.md) (bridge and full storage nodes) | Bonus  | Bonus Pool |
```suggestion
| [Write a technical article](./itn-setup-writeup.md) (bridge and full storage nodes) | Bonus  | Bonus pool |
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/itn-claim-rewards.md
> +## Judging Criteria
```suggestion
## Judging criteria
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/itn-claim-rewards.md
> +## How to Submit
```suggestion
## How to submit
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/itn-deploy-bridge.md
> +# Deploy A Bridge Node
```suggestion
# Deploy a bridge node
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/itn-deploy-light.md
> +## Judging Criteria
```suggestion
## Judging criteria
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/itn-node-analysis.md
> +# Perform Analysis of Your Node
```suggestion
# Perform analysis of your node
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/itn-node-analysis.md
> +## How to Submit
```suggestion
## How to submit
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/itn-pfb-ui.md
> +# Create a UI for Submitting PayForBlob Transactions
```suggestion
# Create a UI for submitting PayForBlob transactions
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/itn-pfb-ui.md
> +## Judging Criteria
```suggestion
## Judging criteria
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/itn-rpc-node.md
> +# Run a Public RPC Node
```suggestion
# Run a public RPC node
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/itn-rpc-node.md
> +## Judging Criteria
```suggestion
## Judging criteria
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/itn-rpc-node.md
> +## How to Submit
```suggestion
## How to submit
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/itn-toolings.md
> +# Create Toolings for the Celestia Network
```suggestion
# Create toolings for the Celestia Network
```

2023-03-27 16:12 UTC, jcstein commented on docs/nodes/itn-toolings.md
> +## Judging Criteria
```suggestion
## Judging criteria
```

2023-03-27 16:14 UTC, jcstein requested changes
added some changes in sentence case

2023-03-28 10:39 UTC, mindstyle85 commented on docs/nodes/itn-enable-telemetry-nodes.md
> +
I would add point 4 here:

4. Make sure you can see your node ID on [https://tiascan.com](https://tiascan.com/) in your respective node category. You can also check your node uptime status there.

2023-03-28 10:51 UTC, jcstein approved these changes

2023-03-29 14:38 UTC, merged